name: 'build'
on: [ 'push', 'pull_request' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout-repo'
        uses: actions/checkout@v2

      - name: 'setup-jdk'
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: 'compile'
        run: |
          chmod +x gradlew
          ./gradlew shadowJar
